// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: password_credential.sql

package db

import (
	"context"
)

const createPasswordCredential = `-- name: CreatePasswordCredential :one
INSERT INTO password_credentials (user_id, password_hash, password_algo)
VALUES ($1, $2, $3)
RETURNING id, email, email_verified_at, user_id, password_hash, password_algo, password_updated_at, created_at, updated_at
`

type CreatePasswordCredentialParams struct {
	UserID       int64  `json:"user_id"`
	PasswordHash string `json:"password_hash"`
	PasswordAlgo string `json:"password_algo"`
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, createPasswordCredential, arg.UserID, arg.PasswordHash, arg.PasswordAlgo)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordAlgo,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePasswordCredential = `-- name: DeletePasswordCredential :one
DELETE FROM password_credentials WHERE id = $1 RETURNING id, email, email_verified_at, user_id, password_hash, password_algo, password_updated_at, created_at, updated_at
`

func (q *Queries) DeletePasswordCredential(ctx context.Context, id int64) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, deletePasswordCredential, id)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordAlgo,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordCredentialByEmail = `-- name: GetPasswordCredentialByEmail :one
SELECT id, email, email_verified_at, user_id, password_hash, password_algo, password_updated_at, created_at, updated_at FROM password_credentials WHERE email = $1 LIMIT 1
`

func (q *Queries) GetPasswordCredentialByEmail(ctx context.Context, email string) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByEmail, email)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordAlgo,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordCredentialByUserID = `-- name: GetPasswordCredentialByUserID :one
SELECT id, email, email_verified_at, user_id, password_hash, password_algo, password_updated_at, created_at, updated_at FROM password_credentials WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetPasswordCredentialByUserID(ctx context.Context, userID int64) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByUserID, userID)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordAlgo,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordCredential = `-- name: UpdatePasswordCredential :one
UPDATE password_credentials
SET password_hash = $2, password_algo = $3, password_updated_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, email, email_verified_at, user_id, password_hash, password_algo, password_updated_at, created_at, updated_at
`

type UpdatePasswordCredentialParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
	PasswordAlgo string `json:"password_algo"`
}

func (q *Queries) UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, updatePasswordCredential, arg.ID, arg.PasswordHash, arg.PasswordAlgo)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordAlgo,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
