// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserIdentity = `-- name: CreateUserIdentity :one
INSERT INTO user_identities (user_id, provider, provider_sub, provider_email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_sub, provider_email, created_at, updated_at
`

type CreateUserIdentityParams struct {
	UserID        int64        `json:"user_id"`
	Provider      AuthProvider `json:"provider"`
	ProviderSub   string       `json:"provider_sub"`
	ProviderEmail pgtype.Text  `json:"provider_email"`
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createUserIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSub,
		arg.ProviderEmail,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSub,
		&i.ProviderEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserIdentitiesByUserID = `-- name: DeleteUserIdentitiesByUserID :many
DELETE FROM user_identities WHERE user_id = $1 RETURNING id, user_id, provider, provider_sub, provider_email, created_at, updated_at
`

func (q *Queries) DeleteUserIdentitiesByUserID(ctx context.Context, userID int64) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, deleteUserIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSub,
			&i.ProviderEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserIdentity = `-- name: DeleteUserIdentity :one
DELETE FROM user_identities WHERE id = $1 RETURNING id, user_id, provider, provider_sub, provider_email, created_at, updated_at
`

func (q *Queries) DeleteUserIdentity(ctx context.Context, id int64) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, deleteUserIdentity, id)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSub,
		&i.ProviderEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIdentitiesByUserID = `-- name: GetUserIdentitiesByUserID :many
SELECT id, user_id, provider, provider_sub, provider_email, created_at, updated_at FROM user_identities WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetUserIdentitiesByUserID(ctx context.Context, userID int64) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, getUserIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSub,
			&i.ProviderEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIdentityByProviderAndSub = `-- name: GetUserIdentityByProviderAndSub :one
SELECT id, user_id, provider, provider_sub, provider_email, created_at, updated_at FROM user_identities WHERE provider = $1 AND provider_sub = $2 LIMIT 1
`

type GetUserIdentityByProviderAndSubParams struct {
	Provider    AuthProvider `json:"provider"`
	ProviderSub string       `json:"provider_sub"`
}

func (q *Queries) GetUserIdentityByProviderAndSub(ctx context.Context, arg GetUserIdentityByProviderAndSubParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByProviderAndSub, arg.Provider, arg.ProviderSub)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSub,
		&i.ProviderEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserIdentity = `-- name: UpdateUserIdentity :one
UPDATE user_identities
SET provider_email = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, provider, provider_sub, provider_email, created_at, updated_at
`

type UpdateUserIdentityParams struct {
	ID            int64       `json:"id"`
	ProviderEmail pgtype.Text `json:"provider_email"`
}

func (q *Queries) UpdateUserIdentity(ctx context.Context, arg UpdateUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, updateUserIdentity, arg.ID, arg.ProviderEmail)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSub,
		&i.ProviderEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
