name: Deploy to staging gcp artifact registry

on:
  push:
    branches:
      - main
      - develop

env:
  DEPLOY_ENV: staging

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: ${{ steps.deploy-to-staging.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: build and push docker image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev
          docker build -t asia-east1-docker.pkg.dev/${GCP_PROJECT_ID}/blipin-backend/blipin-backend:latest .
          docker push asia-east1-docker.pkg.dev/${GCP_PROJECT_ID}/blipin-backend/blipin-backend:latest
